---
- hosts: virtualmachines
  gather_facts: false
  tasks:
    - name: create a new VM
      openstack.cloud.server:
        auth:
         auth_url: https://adacloud.hpc.cineca.it:5000
         username: "igentile"
         password: ""
         project_id: "03d6cf914517413cb6fb2e251d321a74"
         project_name: "EUCC_dtwin"
         user_domain_name: "CINECA"
         project_domain_id: "02490efae3314c4c8b03d044131f3292"
        state: present
        name: my_vm
        image: "CentOS-7-x86_64-GenericCloud-2009"
        flavor_ram: 4096
        key_name: "ikey"
        network: "dtwin_net"
        security_groups: "dtwin_secure1"
        auto_ip: yes

